//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.21 at 01:36:14 PM PDT 
//


package me.bhattsachin.fiveoneone.traffic.model.path;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bhattsachin.fiveoneone.traffic.model.path package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bhattsachin.fiveoneone.traffic.model.path
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Paths }
     * 
     */
    public Paths createPaths() {
        return new Paths();
    }

    /**
     * Create an instance of {@link Paths.Path }
     * 
     */
    public Paths.Path createPathsPath() {
        return new Paths.Path();
    }

    /**
     * Create an instance of {@link Paths.Path.Segments }
     * 
     */
    public Paths.Path.Segments createPathsPathSegments() {
        return new Paths.Path.Segments();
    }

    /**
     * Create an instance of {@link Paths.Path.Incidents }
     * 
     */
    public Paths.Path.Incidents createPathsPathIncidents() {
        return new Paths.Path.Incidents();
    }

    /**
     * Create an instance of {@link Paths.Path.Segments.Segment }
     * 
     */
    public Paths.Path.Segments.Segment createPathsPathSegmentsSegment() {
        return new Paths.Path.Segments.Segment();
    }

}
