//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.21 at 01:36:14 PM PDT 
//


package me.bhattsachin.fiveoneone.traffic.model.path;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="path" maxOccurs="10"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="currentTravelTime" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
 *                   &lt;element name="typicalTravelTime" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
 *                   &lt;element name="miles" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *                   &lt;element name="segments"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="segment" maxOccurs="unbounded"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="road" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="minSpeed" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="maxSpeed" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="avgSpeed" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="incidents"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="incident" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "path"
})
@XmlRootElement(name = "paths")
public class Paths {

    @XmlElement(required = true)
    protected List<Paths.Path> path;

    /**
     * Gets the value of the path property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the path property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPath().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Paths.Path }
     * 
     * 
     */
    public List<Paths.Path> getPath() {
        if (path == null) {
            path = new ArrayList<Paths.Path>();
        }
        return this.path;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="currentTravelTime" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
     *         &lt;element name="typicalTravelTime" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
     *         &lt;element name="miles" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
     *         &lt;element name="segments"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="segment" maxOccurs="unbounded"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="road" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="minSpeed" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="maxSpeed" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="avgSpeed" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="incidents"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="incident" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "currentTravelTime",
        "typicalTravelTime",
        "miles",
        "segments",
        "incidents"
    })
    public static class Path {

        @XmlSchemaType(name = "unsignedByte")
        protected short currentTravelTime;
        @XmlSchemaType(name = "unsignedByte")
        protected short typicalTravelTime;
        @XmlElement(required = true)
        protected BigDecimal miles;
        @XmlElement(required = true)
        protected Paths.Path.Segments segments;
        @XmlElement(required = true)
        protected Paths.Path.Incidents incidents;

        /**
         * Gets the value of the currentTravelTime property.
         * 
         */
        public short getCurrentTravelTime() {
            return currentTravelTime;
        }

        /**
         * Sets the value of the currentTravelTime property.
         * 
         */
        public void setCurrentTravelTime(short value) {
            this.currentTravelTime = value;
        }

        /**
         * Gets the value of the typicalTravelTime property.
         * 
         */
        public short getTypicalTravelTime() {
            return typicalTravelTime;
        }

        /**
         * Sets the value of the typicalTravelTime property.
         * 
         */
        public void setTypicalTravelTime(short value) {
            this.typicalTravelTime = value;
        }

        /**
         * Gets the value of the miles property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getMiles() {
            return miles;
        }

        /**
         * Sets the value of the miles property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setMiles(BigDecimal value) {
            this.miles = value;
        }

        /**
         * Gets the value of the segments property.
         * 
         * @return
         *     possible object is
         *     {@link Paths.Path.Segments }
         *     
         */
        public Paths.Path.Segments getSegments() {
            return segments;
        }

        /**
         * Sets the value of the segments property.
         * 
         * @param value
         *     allowed object is
         *     {@link Paths.Path.Segments }
         *     
         */
        public void setSegments(Paths.Path.Segments value) {
            this.segments = value;
        }

        /**
         * Gets the value of the incidents property.
         * 
         * @return
         *     possible object is
         *     {@link Paths.Path.Incidents }
         *     
         */
        public Paths.Path.Incidents getIncidents() {
            return incidents;
        }

        /**
         * Sets the value of the incidents property.
         * 
         * @param value
         *     allowed object is
         *     {@link Paths.Path.Incidents }
         *     
         */
        public void setIncidents(Paths.Path.Incidents value) {
            this.incidents = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="incident" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "incident"
        })
        public static class Incidents {

            protected List<String> incident;

            /**
             * Gets the value of the incident property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the incident property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getIncident().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getIncident() {
                if (incident == null) {
                    incident = new ArrayList<String>();
                }
                return this.incident;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="segment" maxOccurs="unbounded"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="road" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="minSpeed" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="maxSpeed" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="avgSpeed" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "segment"
        })
        public static class Segments {

            @XmlElement(required = true)
            protected List<Paths.Path.Segments.Segment> segment;

            /**
             * Gets the value of the segment property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the segment property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSegment().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Paths.Path.Segments.Segment }
             * 
             * 
             */
            public List<Paths.Path.Segments.Segment> getSegment() {
                if (segment == null) {
                    segment = new ArrayList<Paths.Path.Segments.Segment>();
                }
                return this.segment;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="road" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="minSpeed" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="maxSpeed" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="avgSpeed" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "road",
                "minSpeed",
                "maxSpeed",
                "avgSpeed"
            })
            public static class Segment {

                @XmlElement(required = true)
                protected String road;
                @XmlElement(required = true)
                protected String minSpeed;
                @XmlElement(required = true)
                protected String maxSpeed;
                @XmlElement(required = true)
                protected String avgSpeed;

                /**
                 * Gets the value of the road property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRoad() {
                    return road;
                }

                /**
                 * Sets the value of the road property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRoad(String value) {
                    this.road = value;
                }

                /**
                 * Gets the value of the minSpeed property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMinSpeed() {
                    return minSpeed;
                }

                /**
                 * Sets the value of the minSpeed property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMinSpeed(String value) {
                    this.minSpeed = value;
                }

                /**
                 * Gets the value of the maxSpeed property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMaxSpeed() {
                    return maxSpeed;
                }

                /**
                 * Sets the value of the maxSpeed property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMaxSpeed(String value) {
                    this.maxSpeed = value;
                }

                /**
                 * Gets the value of the avgSpeed property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAvgSpeed() {
                    return avgSpeed;
                }

                /**
                 * Sets the value of the avgSpeed property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAvgSpeed(String value) {
                    this.avgSpeed = value;
                }

            }

        }

    }

}
